#:schema node_modules/wrangler/config-schema.json
name = "runner-fe"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# Preview ---------------------------------------------------------------------
# [env.preview.vars]
# PUBLIC_API_URL = "https://api.runner.carhart.dev"

# Production ------------------------------------------------------------------
[env.production.vars]
PUBLIC_API_URL = "https://api.runner.carhart.dev"