name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN  }} # CF Deployment
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # CF Deployment
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }} # Turbo Remote Cache
      TURBO_TEAM: ${{ vars.TURBO_TEAM }} # Turbo Remote Cache
      # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Deploy affected
        run: pnpx turbo run deploy --affected

      # - name: Check deploy API
      #   id: affected-api
      #   run: pnpx turbo-ignore @runner/api
      #   continue-on-error: true

      #   # Deploy API if changed
      # - name: Deploy API
      #   working-directory: apps/api
      #   # if: steps.affected-api.outcome == 'failure'
      #   run: |
      #     echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .dev.vars.prod
      #     echo "POSTMARK_SERVER_TOKEN=${{ secrets.POSTMARK_SERVER_TOKEN }}" >> .dev.vars.prod
      #     pnpx wrangler deploy --env prod
