name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN  }} # CF Deployment
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # CF Deployment
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }} # Turbo Remote Cache
      TURBO_TEAM: ${{ vars.TURBO_TEAM }} # Turbo Remote Cache

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Deploy API
        run: pnpx turbo-ignore @runner/api --task=deploy
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
